In [1]:
import pandas as pd

# 0. Importing and Observing Data

In [2]:
df = pd.read_csv('U.S._Chronic_Disease_Indicators__CDI___2023_Release_20240923.csv')
df

/var/folders/qx/nh4cmtrs2vn5wprmsymrdxw80000gn/T/ipykernel_24780/1320837822.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('U.S._Chronic_Disease_Indicators__CDI___2023_Release_20240923.csv')

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2014,2014,AR,Arkansas,SEDD; SID,Asthma,Hospitalizations for asthma,NaN,NaN,Number,...,5,AST,AST3_1,NMBR,GENDER,GENM,NaN,NaN,NaN,NaN
1,2018,2018,CO,Colorado,SEDD; SID,Asthma,Hospitalizations for asthma,NaN,NaN,Number,...,8,AST,AST3_1,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2018,2018,DC,District of Columbia,SEDD; SID,Asthma,Hospitalizations for asthma,NaN,NaN,Number,...,11,AST,AST3_1,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2017,2017,GA,Georgia,SEDD; SID,Asthma,Hospitalizations for asthma,NaN,NaN,Number,...,13,AST,AST3_1,NMBR,GENDER,GENF,NaN,NaN,NaN,NaN
4,2010,2010,MI,Michigan,SEDD; SID,Asthma,Hospitalizations for asthma,NaN,NaN,Number,...,26,AST,AST3_1,NMBR,RACE,HIS,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1185671,2020,2020,WY,Wyoming,BRFSS,Diabetes,Dilated eye examination among adults aged >= 1...,NaN,%,Age-adjusted Prevalence,...,56,DIA,DIA7_0,AGEADJPREV,RACE,WHT,NaN,NaN,NaN,NaN
1185672,2020,2020,WY,Wyoming,BRFSS,Older Adults,Proportion of older adults aged >= 65 years wh...,NaN,%,Crude Prevalence,...,56,OLD,OLD3_1,CRDPREV,RACE,WHT,NaN,NaN,NaN,NaN
1185673,2017,2017,IA,Iowa,BRFSS,Arthritis,Activity limitation due to arthritis among adu...,NaN,%,Age-adjusted Prevalence,...,19,ART,ART2_1,AGEADJPREV,RACE,HIS,NaN,NaN,NaN,NaN
1185674,2020,2020,WY,Wyoming,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,Crude Prevalence,...,56,DIA,DIA2_2,CRDPREV,RACE,HIS,NaN,NaN,NaN,NaN
1185675,2019,2019,RI,Rhode Island,BRFSS,Arthritis,Activity limitation due to arthritis among adu...,NaN,%,Crude Prevalence,...,44,ART,ART2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [3]:
df.shape

(1185676, 34)

In [4]:
df.columns

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'DataSource',
       'Topic', 'Question', 'Response', 'DataValueUnit', 'DataValueType',
       'DataValue', 'DataValueAlt', 'DataValueFootnoteSymbol',
       'DatavalueFootnote', 'LowConfidenceLimit', 'HighConfidenceLimit',
       'StratificationCategory1', 'Stratification1', 'StratificationCategory2',
       'Stratification2', 'StratificationCategory3', 'Stratification3',
       'GeoLocation', 'ResponseID', 'LocationID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'StratificationCategoryID1', 'StratificationID1',
       'StratificationCategoryID2', 'StratificationID2',
       'StratificationCategoryID3', 'StratificationID3'],
      dtype='object')

# 1. Select Relevant Columns

In [5]:
# find unique values that include "binge drinking" and "poverty"
df['Question'].unique()

array(['Hospitalizations for asthma', 'Asthma mortality rate',
       'Cancer of the oral cavity and pharynx, mortality',
       'Cancer of the prostate, mortality',
       'Invasive cancer (all sites combined), mortality',
       'Cancer of the female breast, mortality',
       'Cancer of the female cervix, mortality',
       'Cancer of the colon and rectum (colorectal), mortality',
       'Cancer of the lung and bronchus, mortality',
       'Invasive melanoma, incidence', 'Melanoma, mortality',
       'Mortality with end-stage renal disease',
       'Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis',
       'Hospitalization for chronic obstructive pulmonary disease as any diagnosis',
       'Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis among Medicare-eligible persons aged >= 65 years',
       'Hospitalization for chronic obstructive pulmonary disease as any diagnosis among Medicare-eligible persons aged >= 65 years',
       'Mortality from heart failure',
       'Hospitalization for heart failure among Medicare-eligible persons aged >= 65 years',
       'Hospitalization for stroke', 'Pre-pregnancy hypertension',
       'Mortality due to diabetes reported as any listed cause of death',
       'Mortality with diabetic ketoacidosis reported as any listed cause of death',
       'Amputation of a lower extremity attributable to diabetes',
       'Hospitalization with diabetes as a listed diagnosis',
       'Disability among adults aged >= 65 years',
       'Folic acid supplementation', 'Sale of cigarette packs',
       'Chronic liver disease mortality', 'Alcohol use before pregnancy',
       'Alcohol use among youth',
       'Local authority to regulate alcohol outlet density',
       'Binge drinking prevalence among youth',
       'Emergency department visit rate for asthma',
       'Adults aged >= 18 years with arthritis who have taken a class to learn how to manage arthritis symptoms',
       'Amount of alcohol excise tax by beverage type (beer)',
       'Amount of alcohol excise tax by beverage type (wine)',
       'Amount of alcohol excise tax by beverage type (distilled spirits)',
       'Commercial host (dram shop) liability laws',
       'Per capita alcohol consumption among persons aged >= 14 years',
       'Invasive cancer of the oral cavity or pharynx, incidence',
       'Invasive cancer of the prostate, incidence',
       'Invasive cancer (all sites combined), incidence',
       'Invasive cancer of the female breast, incidence',
       'Invasive cancer of the cervix, incidence',
       'Cancer of the colon and rectum (colorectal), incidence',
       'Cancer of the lung and bronchus, incidence',
       'Incidence of treated end-stage renal disease',
       'Mortality with chronic obstructive pulmonary disease as underlying cause among adults aged >= 45 years',
       'Incidence of treated end-stage renal disease attributed to diabetes',
       'Mortality with chronic obstructive pulmonary disease as underlying or contributing cause among adults aged >= 45 years',
       'Mortality from total cardiovascular diseases',
       'Mortality from diseases of the heart',
       'Mortality from coronary heart disease',
       'Emergency department visit rate for chronic obstructive pulmonary disease as first-listed diagnosis',
       'Emergency department visit rate for chronic obstructive pulmonary disease as any diagnosis',
       'Mortality from cerebrovascular disease (stroke)',
       'Prevalence of pre-pregnancy diabetes',
       'Hospitalization for acute myocardial infarction',
       'Prevalence of gestational diabetes', 'Postpartum checkup',
       'Amount of tobacco product excise tax',
       'Cigarette smoking before pregnancy',
       'Current cigarette smoking among youth',
       'Participation in daily school physical education classes among high school students',
       'Live births occurring at Baby Friendly Facilities',
       'Soda consumption among high school students',
       'Meeting aerobic physical activity guidelines among high school students',
       'Secondary schools that allow community-sponsored use of physical activity facilities by youth outside of normal school hours',
       'Infants breastfed at 6 months',
       'Receiving formula supplementation within the first 2 days of life among breastfed infants',
       'Mean maternity practices in infant nutrition care (mPINC) score',
       'Secondary schools that allow students to purchase soda or fruit drinks',
       'Secondary schools that offer less healthy foods as competitive foods',
       'Presence of regulations pertaining to screen time in early care and education settings',
       'Postpartum depressive symptoms',
       'Secondary schools that allow students to purchase sports drinks',
       'State child care regulation supports onsite breastfeeding',
       'Computer use among high school students',
       'Television viewing among high school students',
       'Median daily frequency of vegetable consumption among high school students',
       'Obesity among high school students',
       'Hospitalization for hip fracture among Medicare-eligible persons aged >= 65 years',
       'Presence of regulations pertaining to avoiding sugar in early care and education settings',
       'Overweight or obesity among high school students',
       'Median daily frequency of fruit consumption among high school students',
       'Number of farmers markets per 100,000 residents',
       'Healthy weight among high school students',
       'Census tracts with healthier food retailers within � mile of boundary',
       'Farmers markets that accept Women and Infant Children (WIC) farmers market nutrition program coupons',
       'Oral health services at Federally Qualified Health Centers',
       'Presence of regulations pertaining to serving fruit in early care and education settings',
       'Presence of regulations pertaining to serving vegetables in early care and education settings',
       'Farmers markets that accept Supplemental Nutrition Assistance Program (SNAP) benefits',
       'Life expectancy at birth',
       'Premature mortality among adults aged 45-64 years', 'Poverty',
       'Preventive dental care before pregnancy',
       'Life expectancy at age 65 years',
       'Prevalence of 2 or more chronic conditions among Medicare-enrolled persons aged >= 65 years',
       'High school completion among adults aged 18-24 years',
       'Dental visits among children and adolescents aged 1-17 years',
       'High school completion among women aged 18-44 years',
       'Health insurance coverage before pregnancy',
       'Poverty among women aged 18-44 years',
       'Preventive dental visits among children and adolescents aged 1-17 years',
       'Population served by community water systems that receive fluoridated drinking water',
       'Gini Index of income inequality',
       'States that allow stronger local tobacco control and prevention laws',
       'Current smokeless tobacco use among youth',
       'States with strong polices that require retail licenses to sell tobacco products',
       'Proportion of the population protected by a comprehensive smoke-free policy prohibiting smoking in all indoor areas of workplaces and public places, including restaurants and bars',
       'Secondary schools that have a comprehensive tobacco-free school policy in place',
       'Percent tobacco revenue to fund at CDC recommended level',
       'Asthma prevalence among women aged 18-44 years',
       'Heavy drinking among adults aged >= 18 years',
       'Diabetes prevalence among women aged 18-44 years',
       'Current smoking among adults aged >= 18 years',
       'All teeth lost among adults aged >= 65 years',
       'Arthritis among adults aged >= 18 years',
       'No tooth loss among adults aged 18-64 years',
       'Current asthma prevalence among adults aged >= 18 years',
       'Mammography use among women aged 50-74 years',
       'Prevalence of chronic kidney disease among adults aged >= 18 years',
       'Cholesterol screening among adults aged >= 18 years',
       'Foot examination among adults aged >= 18 years with diagnosed diabetes',
       'Arthritis among adults aged >= 18 years who have diabetes',
       'Quit attempts in the past year among current smokers',
       'Dilated eye examination among adults aged >= 18 years with diagnosed diabetes',
       'Recent mentally unhealthy days among adults aged >= 18 years',
       'Heavy drinking among women aged 18-44 years',
       'Arthritis among adults aged >= 18 years who are obese',
       'Binge drinking intensity among adults aged >= 18 years who binge drink',
       'Arthritis among adults aged >= 18 years who have heart disease',
       'Overweight or obesity among adults aged >= 18 years',
       'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes',
       'Current health care coverage among women aged 18-44 years',
       'Current smokeless tobacco use among adults aged >= 18 years',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with a history of coronary heart disease',
       'Influenza vaccination among noninstitutionalized adults aged 18-64 years with a history of coronary heart disease or stroke',
       'Awareness of high blood pressure among women aged 18-44 years',
       'Recent activity limitation among adults aged >= 18 years',
       'Self-rated health status among women aged 18-44 years',
       'Current lack of health insurance among adults aged 18-64 years',
       'At least 14 recent mentally unhealthy days among women aged 18-44 years',
       'Obesity among adults aged >= 18 years',
       'Binge drinking frequency among adults aged >= 18 years who binge drink',
       'High cholesterol prevalence among adults aged >= 18 years',
       'Taking medicine for high blood pressure control among adults aged >= 18 years with high blood pressure',
       'Visits to dentist or dental clinic among adults aged >= 18 years',
       'Physical inactivity among adults aged >= 18 years with arthritis',
       'Adults with diagnosed diabetes aged >= 18 years who have taken a diabetes self-management course',
       'Fecal occult blood test, sigmoidoscopy, or colonoscopy among adults aged 50-75 years',
       'Prevalence of chronic obstructive pulmonary disease among adults >= 18',
       'Prevalence of chronic obstructive pulmonary disease among adults >= 45 years',
       'Work limitation due to arthritis among adults aged 18-64 years who have doctor-diagnosed arthritis',
       'Median daily frequency of vegetable consumption among adults aged >= 18 years',
       'Median daily frequency of fruit consumption among adults aged >= 18 years',
       'Prevalence of current smoking among adults >= 45 years with diagnosed chronic obstructive pulmonary disease',
       'Influenza vaccination among noninstitutionalized adults aged >= 18 years',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years who smoke',
       'Prevalence of current smoking among adults >= 18 with diagnosed chronic obstructive pulmonary disease',
       'Prevalence of depressive disorders among adults aged >= 18 years with diagnosed diabetes',
       'Glycosylated hemoglobin measurement among adults aged >= 18 years with diagnosed diabetes',
       'Influenza vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes',
       'No leisure-time physical activity among adults aged >= 18 years',
       'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with a history of coronary heart disease',
       'Awareness of high blood pressure among adults aged >= 18 years',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes',
       'Influenza vaccination among noninstitutionalized adults aged >= 65 years with a history of coronary heart disease or stroke',
       'Binge drinking prevalence among adults aged >= 18 years',
       'Meeting aerobic physical activity guidelines for additional and more extensive health benefits among adults aged >= 18 years',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease',
       'Six or more teeth lost among adults aged >= 65 years',
       'Timeliness of routine health care checkup among women aged 18-44 years',
       'Fair or poor health among adults aged >= 18 years with arthritis',
       'Prevalence of high cholesterol among adults aged >= 18 years with diagnosed diabetes',
       'Influenza vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease',
       'Prevalence of diagnosed diabetes among adults aged >= 18 years',
       'Binge drinking prevalence among women aged 18-44 years',
       'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years who smoke',
       'Proportion of older adults aged 50-64 years who are up to date on a core set of clinical preventive services',
       'Activity limitation due to arthritis among adults aged >= 18 years who have doctor-diagnosed arthritis',
       'Recent physically unhealthy days among adults aged >= 18 years',
       'Influenza vaccination among noninstitutionalized adults aged >= 65 years with asthma',
       'Fair or poor self-rated health status among adults aged >= 18 years',
       'Influenza vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes',
       'Meeting aerobic physical activity guidelines for substantial health benefits among adults aged >= 18 years',
       'Influenza vaccination among noninstitutionalized adults aged 18-64 years with asthma',
       'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with asthma',
       'Recent Papanicolaou smear use among women aged 21-44 years',
       'Prevalence of activity limitation among adults >= 45 years with diagnosed chronic obstructive pulmonary disease',
       'Severe joint pain due to arthritis among adults aged >= 18 years who have doctor-diagnosed arthritis',
       'Healthy weight among adults aged >= 18 years',
       'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with asthma',
       'Prevalence of high blood pressure among adults aged >= 18 years with diagnosed diabetes',
       'Meeting aerobic physical activity guidelines for substantial health benefits and for muscle-strengthening activity among adults aged >= 18 years',
       'Prevalence of sufficient sleep among adults aged >= 18 years',
       'Prevalence of activity limitation among adults >= 18 with diagnosed chronic obstructive pulmonary disease',
       'Overweight or obesity among women aged 18-44 years',
       'Proportion of older adults aged >= 65 years who are up to date on a core set of clinical preventive services',
       'Current cigarette smoking among women aged 18-44 years',
       'Visits to dentist or dental clinic among adults aged >= 18 years with diagnosed diabetes',
       'Papanicolaou smear use among adult women aged 21-65 years'],
      dtype=object)

In [6]:
# select data that is about: 
# Binge drinking prevalence among adults aged >= 18 years (overall, males, females), in crude prevalence percentages.
binge_drinking_crude = df[(df['Question'] == 'Binge drinking prevalence among adults aged >= 18 years')
                         &(df['DataValueTypeID'] == 'CRDPREV')
                         ]
binge_drinking_crude_OveralFM = binge_drinking_crude[(binge_drinking_crude['StratificationCategoryID1'] == 'OVERALL')
                                                    |(binge_drinking_crude['StratificationCategoryID1'] == 'GENDER')
                                                    ]
binge_drinking_crude_OveralFM

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
529731,2021,2021,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
530247,2019,2019,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
530534,2012,2012,AL,Alabama,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
530605,2014,2014,AL,Alabama,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
531039,2011,2011,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1182108,2013,2013,WY,Wyoming,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,56,ALC,ALC2_2,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
1182149,2019,2019,WY,Wyoming,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,56,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1183166,2020,2020,WY,Wyoming,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,56,ALC,ALC2_2,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
1183770,2020,2020,WY,Wyoming,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,56,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1185471,2020,2020,WY,Wyoming,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,56,ALC,ALC2_2,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN

In [7]:
# select data that is about: 
# Poverty prevalence, Crude Prevalence in Percent (overall only).
poverty_crude_overall = df[(df['Question'] == 'Poverty') 
                         & (df['DataValueType'] == 'Crude Prevalence')
                         & (df['StratificationCategoryID1'] == 'OVERALL')
                          ]
poverty_crude_overall2 = poverty_crude_overall.copy()
poverty_crude_overall2['StratificationID1'] = 'poverty'
poverty_crude_overall2

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
463675,2019,2019,OH,Ohio,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,39,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
470247,2018,2018,AL,Alabama,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,1,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
472213,2010,2010,CO,Colorado,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,8,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
473633,2015,2015,TX,Texas,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,48,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
478365,2013,2013,RI,Rhode Island,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,44,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503787,2012,2012,KS,Kansas,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,20,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
503833,2010,2010,DC,District of Columbia,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,11,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
503840,2018,2018,WI,Wisconsin,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,55,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
503846,2012,2012,WA,Washington,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,53,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
503893,2016,2016,AZ,Arizona,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,4,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN

In [8]:
# concat the two dataframe into one df
binge_poverty = pd.concat([binge_drinking_crude_OveralFM, poverty_crude_overall2], axis=0)
binge_poverty

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
529731,2021,2021,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
530247,2019,2019,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
530534,2012,2012,AL,Alabama,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
530605,2014,2014,AL,Alabama,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
531039,2011,2011,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503787,2012,2012,KS,Kansas,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,20,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
503833,2010,2010,DC,District of Columbia,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,11,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
503840,2018,2018,WI,Wisconsin,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,55,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
503846,2012,2012,WA,Washington,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,53,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN
503893,2016,2016,AZ,Arizona,ACS 1-Year Estimates,Overarching Conditions,Poverty,NaN,%,Crude Prevalence,...,4,OVC,OVC3_1,CRDPREV,OVERALL,poverty,NaN,NaN,NaN,NaN

# 2. Reshape the Data

In [21]:
# renaming parts of columns
binge_poverty = binge_poverty.rename(columns={
    'YearEnd': 'year',
    'LocationAbbr': 'stateabb',
    'LocationDesc': 'state',
})
binge_poverty['DataValue'] = binge_poverty['DataValue'].astype(float)


# Convert the dataset from long format to wide format using appropriate pandas commands. 
df_wide = binge_poverty.pivot(index=['year', 'stateabb', 'state'], columns = 'StratificationID1', values = 'DataValue')
df_wide

StratificationID1            GENF  GENM   OVR  poverty
year stateabb state
2010 AK       Alaska          NaN   NaN   NaN      9.9
     AL       Alabama         NaN   NaN   NaN     19.0
     AR       Arkansas        NaN   NaN   NaN     18.8
     AZ       Arizona         NaN   NaN   NaN     17.4
     CA       California      NaN   NaN   NaN     15.8
...                           ...   ...   ...      ...
2021 VT       Vermont        13.8  20.2  17.0      NaN
     WA       Washington     11.7  18.9  15.2      NaN
     WI       Wisconsin      17.9  25.9  21.9      NaN
     WV       West Virginia   7.0  16.5  11.6      NaN
     WY       Wyoming        12.5  19.3  15.9      NaN

[658 rows x 4 columns]

In [22]:
# renaming columns
df_wide = df_wide.rename(columns={
    'GENF': 'binge_female',
    'GENM': 'binge_male',
    'OVR': 'binge_all',
})
df_wide

StratificationID1            binge_female  binge_male  binge_all  poverty
year stateabb state
2010 AK       Alaska                  NaN         NaN        NaN      9.9
     AL       Alabama                 NaN         NaN        NaN     19.0
     AR       Arkansas                NaN         NaN        NaN     18.8
     AZ       Arizona                 NaN         NaN        NaN     17.4
     CA       California              NaN         NaN        NaN     15.8
...                                   ...         ...        ...      ...
2021 VT       Vermont                13.8        20.2       17.0      NaN
     WA       Washington             11.7        18.9       15.2      NaN
     WI       Wisconsin              17.9        25.9       21.9      NaN
     WV       West Virginia           7.0        16.5       11.6      NaN
     WY       Wyoming                12.5        19.3       15.9      NaN

[658 rows x 4 columns]

# 3.Summary of the Cleaned Data

In [23]:
df_wide.shape

(658, 4)

In [24]:
df_wide.describe()

StratificationID1  binge_female  binge_male   binge_all     poverty
count                594.000000  594.000000  594.000000  530.000000
mean                  11.726599   22.064141   16.751515   14.718113
std                    2.781037    3.705719    3.066388    5.245498
min                    5.000000   13.100000    9.600000    7.300000
25%                    9.900000   19.625000   14.825000   11.600000
50%                   11.700000   21.700000   16.600000   13.800000
75%                   13.175000   24.100000   18.400000   16.600000
max                   22.300000   33.800000   27.200000   46.200000

# 4. Save Cleaned Data

In [25]:
df_wide.to_csv('binge_clean.csv', index=True)

# 5.Data Transformation and Analysis

* 5.1 Top 10 States for Binge Drinking

In [44]:
# For the most recent year in the dataset
df_wide2 = df_wide.copy()
df_wide2 = df_wide2.reset_index()
max_year = df_wide2['year'].max()
df_wide_max_year = df_wide2[df_wide2['year'] == max_year]

# create a table showing the top 10 U.S. states with the highest overall binge drinking prevalence.
overall_BD_maxYear = df_wide_max_year.sort_values(by='binge_all', ascending=False)
top_ten = overall_BD_maxYear.head(10)
Top10States_OverallBD_maxYear = top_ten[['year','state','binge_all']]
Top10States_OverallBD_maxYear.index = [i for i in range(1,11)]
Top10State_table = pd.DataFrame(Top10States_OverallBD_maxYear)
Top10State_table

StratificationID1  year                 state  binge_all
1                  2021  District of Columbia       22.5
2                  2021             Wisconsin       21.9
3                  2021          North Dakota       20.8
4                  2021               Montana       20.5
5                  2021                  Iowa       20.1
6                  2021          South Dakota       19.6
7                  2021              Nebraska       19.5
8                  2021              Colorado       18.7
9                  2021             Minnesota       17.9
10                 2021                Kansas       17.7

* 5.2 Annual Growth Rates in Binge Drinking

In [71]:
df_wide3 = df_wide.copy()
df_wide3 = df_wide3.reset_index()
bing_all = df_wide3[['year', 'state','binge_all']]

# Drop rows with missing binge_all values to ensure accurate calculations
bing_all_clean = bing_all.dropna(subset=['binge_all'])

# Sort the data by 'state' and 'year' to ensure pct_change works correctly
bing_all_clean = bing_all_clean.sort_values(['state', 'year'])

# Group by 'state' and calculate the year-over-year percentage change using pct_change
bing_all_clean['pct_change'] = bing_all_clean.groupby('state')['binge_all'].pct_change()

# Now, calculate the average of these percentage changes for each state (AAGR approximation)
aagr_by_state = bing_all_clean.groupby('state')['pct_change'].mean().reset_index()
aagr_by_state.columns = ['state', 'avg_annual_growth_rate']

# top 5
sorted_aagr = aagr_by_state.sort_values(by='avg_annual_growth_rate', ascending=False)
top_5 = sorted_aagr.head(5)
bottom_5 = sorted_aagr.tail(5)

# create table
top_5.index = [i for i in range(1,6)]
bottom_5.index = [i for i in range(1,6)]

Top5State_table = pd.DataFrame(top_5)
bottom5State_table = pd.DataFrame(bottom_5)

Top5State_table

            state  avg_annual_growth_rate
1       Tennessee                0.041212
2   West Virginia                0.016889
3       Louisiana                0.008233
4          Kansas                0.005577
5  North Carolina                0.003030

In [72]:
bottom5State_table

            state  avg_annual_growth_rate
1        Maryland               -0.028802
2        Oklahoma               -0.029134
3        Illinois               -0.034692
4        Delaware               -0.039528
5  Virgin Islands               -0.171053